---
apiVersion: v1
kind: Service
metadata:
  name: {{PROJECTNAME}}-{{ENVIRONMENT}}-back
  namespace: {{PROJECTNAME}}-{{ENVIRONMENT}}
spec:
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: {{PROJECTNAME}}-{{ENVIRONMENT}}-back
