---
apiVersion: v1
kind: Service
metadata:
  name: {{PROJECT_NAME}}-{{ENVIRONMENT}}-back
  namespace: {{PROJECT_NAME}}-{{ENVIRONMENT}}
spec:
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: {{PROJECT_NAME}}-{{ENVIRONMENT}}-back
