apiVersion: v1
kind: ConfigMap
metadata:
  name: {{PROJECTNAME}}-front-{{ENVIRONMENT}}-config
  namespace: {{PROJECTNAME}}-{{ENVIRONMENT}}
data:
  PORT: "3000"
  SESSION_SECRET: "{{SECRETKEY}}"
  BASE_URL_API: ""
  LOGIN_URL: ""
