apiVersion: v1
kind: ConfigMap
metadata:
  name: {{PROJECT_NAME}}-{{ENVIRONMENT}}-front-config
  namespace: {{PROJECT_NAME}}-{{ENVIRONMENT}}
data:
  PORT: "3000"
  SESSION_SECRET: "{{SECRETKEY}}"
  BASE_URL_API: ""
  LOGIN_URL: ""
