apiVersion: v1
kind: ConfigMap
metadata:
  name: {{PROJECT_NAME}}-{{ENVIRONMENT}}-config
  namespace: {{PROJECT_NAME}}-{{ENVIRONMENT}}
data:
  GIN_MODE: "release"
  POSTGRES_DB: "{{PROJECT_NAME}}"
  POSTGRES_USER: user
  POSTGRES_PASSWORD: password
  POSTGRES_HOST: host
  POSTGRES_PORT: "5432"
  KAFKA_BOOTSTRAP_SERVER: "kafkaserver"
  KAFKA_CLIENT_ID: "{{PROJECT_NAME}}-{{ENVIRONMENT}}"
  KAFKA_GROUP_ID: "{{PROJECT_NAME}}-{{ENVIRONMENT}}"
