apiVersion: v1
kind: ConfigMap
metadata:
  name: {{PROJECTNAME}}-{{ENVIRONMENT}}-config
  namespace: {{PROJECTNAME}}-{{ENVIRONMENT}}
data:
  GIN_MODE: "release"
  POSTGRES_DB: "{{PROJECTNAME}}"
  POSTGRES_USER: user
  POSTGRES_PASSWORD: password
  POSTGRES_HOST: host
  POSTGRES_PORT: "5432"
  KAFKA_BOOTSTRAP_SERVER: "kafkaserver"
  KAFKA_CLIENT_ID: "{{PROJECTNAME}}-{{ENVIRONMENT}}"
  KAFKA_GROUP_ID: "{{PROJECTNAME}}-{{ENVIRONMENT}}"
