---
apiVersion: v1
kind: Service
metadata:
  name: {{PROJECTNAME}}-{{ENVIRONMENT}}-front
  namespace: {{PROJECTNAME}}-{{ENVIRONMENT}}
spec:
  ports:
    - port: 80
      targetPort: 3000
  selector:
    app: {{PROJECTNAME}}-{{ENVIRONMENT}}-front
