---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{PROJECT_NAME}}-{{ENVIRONMENT}}-back
  namespace: {{PROJECT_NAME}}-{{ENVIRONMENT}}
  labels:
    app: {{PROJECT_NAME}}-{{ENVIRONMENT}}-back
spec:
  revisionHistoryLimit: 0
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 50%
      maxUnavailable: 50%
  replicas: 1
  selector:
    matchLabels:
      app: {{PROJECT_NAME}}-{{ENVIRONMENT}}-back
  template:
    metadata:
      labels:
        app: {{PROJECT_NAME}}-{{ENVIRONMENT}}-back
    spec:
      containers:
        - name: {{PROJECT_NAME}}-{{ENVIRONMENT}}-back
          image: 197272534240.dkr.ecr.us-east-1.amazonaws.com/{{PROJECT_NAME}}-{{ENVIRONMENT}}:latest
          imagePullPolicy: Always
          readinessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 5
          resources:
            limits:
              cpu: 500m
              memory: 600Mi
            requests:
              cpu: 80m
              memory: 150Mi
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: {{PROJECT_NAME}}-{{ENVIRONMENT}}-config
          volumeMounts:
            - name: config
              mountPath: /etc/localtime
      volumes:
        - name: config
          hostPath:
            path: /usr/share/zoneinfo/America/Sao_Paulo
