apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    kubernetes.io/ingress.class: nginx
  name: {{PROJECTNAME}}-{{ENVIRONMENT}}-back-ingress
  namespace: {{PROJECTNAME}}-{{ENVIRONMENT}}
spec:
  rules:
    - host: {{BACKENDENDPOINT}}
      http:
        paths:
          - backend:
              service:
                name: {{PROJECTNAME}}-{{ENVIRONMENT}}-back
                port:
                  number: 80
            pathType: ImplementationSpecific
  tls:
    - hosts:
        - {{BACKENDENDPOINT}}
      secretName: {{PROJECTNAME}}-{{ENVIRONMENT}}-back-tls
